---
title: "Pokemon Go Type Analysis"
author: "darthaline"
date: "28 Sept 2020"
output:
  html_notebook:
    toc: true
---

## Available data

### DPS data lvl 40

```{r DPSData}
theurl <- "https://gamepress.gg/pokemongo/comprehensive-dps-spreadsheet"
dpsData <- read.csv(file.path('data', 'comprehensive_dps.csv'))
rm(theurl)
dpsData
```

### Typing data

```{r StatsData, eval=FALSE}
theurl <- "https://www.kaggle.com/netzuel/pokmon-go-dataset-15-generations"
statsData <- read.csv(file.path('data', 'pogo.csv'))
rm(theurl)
statsData$Secondary[statsData$Secondary == 'None'] <- NA
statsData$Primary <- tolower(statsData$Primary)
statsData$Secondary <- tolower(statsData$Secondary)
statsData
```

```{r typeList, eval=FALSE}
types <- as.character(unique(statsData$Primary))
types <- tolower(types)
types <- sort(types)
types
```

```{r typeData}
library(rvest)

theurl <- "https://pokemondb.net/pokedex/all"
source_tables <- read_html(theurl)
typeData <- html_nodes(source_tables, ".data-table")
typeData <- html_table(typeData[[1]], fill = TRUE)
typeData$Type <- tolower(typeData$Type)

write.table(typeData, file = file.path('data', 'pokedex.csv'), sep = ',', row.names=FALSE)

rm(theurl, source_tables)
```

### Effectiveness data

```{r effectivenessData}
theurl <- "https://docs.google.com/spreadsheets/d/1dlXr-i300HAWEekKQltdJQsll7keoKhsjuRDKft2F0U/edit?usp=sharing"
effectivenessData <- read.csv(file.path('data', 'pokemon go type effectiveness chart.csv'), skip = 4)
rm(theurl)

effectivenessData <- effectivenessData[!names(effectivenessData) %in% c('poison.dark', 'geom.att')]
effectivenessData <- effectivenessData[-dim(effectivenessData)[2],]
effectivenessData
```

```{r}
effectivenessDataTransposed <- t(effectivenessData)
colnames(effectivenessDataTransposed) <- effectivenessDataTransposed[1,]
rownames(effectivenessDataTransposed) <- c('defending.attacking', as.character(effectivenessData$attacking.defending))
effectivenessDataTransposed <- effectivenessDataTransposed[rownames(effectivenessDataTransposed) !='defending.attacking',]
effectivenessDataTransposed <- data.frame(effectivenessDataTransposed,
                                          stringsAsFactors = FALSE) #defending\attacking order
effectivenessDataTransposed
```

```{r}
types <-c("bug","dark","dragon","electric",
          "fairy","fighting","fire","flying",
          "ghost","grass","ground","ice",
          "normal","poison","psychic","rock",
          "steel","water")
```

```{r}
library(utils)
dualTypeDefenders <- combn(types, 2)
dualTypeDefenders <- t(dualTypeDefenders)
dualTypeDefenders <- data.frame(dualTypeDefenders)
colnames(dualTypeDefenders) <- c('first', 'second')
dualTypeDefenders$first <- as.character(dualTypeDefenders$first)
dualTypeDefenders$second <- as.character(dualTypeDefenders$second)
```

```{r}
fullDefendingTable <- data.frame(primary = rownames(effectivenessDataTransposed),
                                 secondary = NA,
                                 effectivenessDataTransposed,
                                 stringsAsFactors = FALSE)
fullDefendingTableColnames <- colnames(fullDefendingTable)

for (i in 1:dim(dualTypeDefenders)[1]){
    if(dualTypeDefenders$first[i] == dualTypeDefenders$second[i]) {
        
        cleanRow <- as.character(unname(unlist( effectivenessDataTransposed[rownames(effectivenessDataTransposed) == dualTypeDefenders$first[i],] )))
        
        fullDefendingTable <- rbind(fullDefendingTable,
                                    c(dualTypeDefenders$first[i],
                                      NA,
                                      cleanRow),
                                    stringsAsFactors = FALSE)
    } else {
        multiplied <- as.numeric(unlist(effectivenessDataTransposed[rownames(effectivenessDataTransposed) == dualTypeDefenders$first[i],])) *
                      as.numeric(unlist(effectivenessDataTransposed[rownames(effectivenessDataTransposed) == dualTypeDefenders$second[i],]))
        
        fullDefendingTable <- rbind(fullDefendingTable,
                                    c(dualTypeDefenders$first[i],
                                      dualTypeDefenders$second[i],
                                      multiplied),
                                    stringsAsFactors = FALSE)
    }
}

colnames(fullDefendingTable) <- fullDefendingTableColnames

rm(dualTypeDefenders, multiplied, effectivenessDataTransposed, types, i)

rownames(fullDefendingTable) <- c()
fullDefendingTable
```


### Moves Data

```{r movesData}
library(rvest)

theurl <- "https://pokemon.gameinfo.io/en/moves"
source_tables <- read_html(theurl)
movesData <- html_nodes(source_tables, ".sortable")
movesDataIcon <- html_nodes(source_tables, ".move-icon")
movesDataIcon <- html_attr(movesDataIcon, 'data-type')
movesDataIcon <- tolower(movesDataIcon)

fastMovesData  <- html_table(movesData[[1]], fill = TRUE)
colnames(fastMovesData) <- c('Type', colnames(fastMovesData)[2:4])
chargedMovesData  <- html_table(movesData[[2]], fill = TRUE)
colnames(chargedMovesData) <- c('Type', colnames(chargedMovesData)[2:4])

fastMovesData$Type <- movesDataIcon[ 1:dim(fastMovesData)[1] ]
chargedMovesData$Type <- movesDataIcon[ (dim(fastMovesData)[1]+1): (dim(fastMovesData)[1]+dim(chargedMovesData)[1])]

write.table(fastMovesData, file = file.path('data', 'fastMovesData.csv'), sep = ',', row.names=FALSE)
write.table(chargedMovesData, file = file.path('data', 'chargedMovesData.csv'), sep = ',', row.names=FALSE)

rm(theurl, source_tables, movesData, movesDataIcon)
```

```{r fastMovesData}
fastMovesData
```

```{r chargedMovesData}
chargedMovesData
```

## Analysis

### Resistor Types

```{r moveTypeInputs}
#input 2 movetypes, sort alphabetically
moveTypes <- c('poison', 'dark')
#moveTypes <- c('ghost', 'psychic')
moveTypes <- sort(moveTypes)
moveTypes
```

```{r}
defendingRow <- fullDefendingTable[fullDefendingTable$primary == moveTypes[1] &
                                       fullDefendingTable$secondary == moveTypes[2] &
                                       !is.na(fullDefendingTable$secondary),]
defendingRow <- rbind(defendingRow,
                      fullDefendingTable[fullDefendingTable$primary == moveTypes[2] &
                                             fullDefendingTable$secondary == moveTypes[1] &
                                             !is.na(fullDefendingTable$secondary),])
defendingRow
```


```{r, warning=FALSE}
#selecting moveTypes
tempEffectiveness <- effectivenessData[effectivenessData$attacking.defending %in% moveTypes,]

# calculating the product of the two movetypes
tempEffectivenessProduct <- unlist(lapply(tempEffectiveness[!names(tempEffectiveness) %in% c('attacking.defending')], prod))

# removing factoring
tempEffectiveness$attacking.defending <- as.character(tempEffectiveness$attacking.defending)

#merging movetypes to make a name in the data frame
rowtitleProduct <- paste(moveTypes, collapse = ' & ')
tempEffectiveness <- rbind(tempEffectiveness, c(rowtitleProduct, tempEffectivenessProduct))
tempEffectiveness
```

```{r}
# selecting columns which provide defence against combination of those move types
tempEffectivenessResistant <- tempEffectiveness[, colnames(tempEffectiveness) == 'attacking.defending' |
                                         tempEffectiveness[tempEffectiveness$attacking.defending == rowtitleProduct,] < 1]
tempEffectivenessResistant
rm(tempEffectivenessProduct, rowtitleProduct)
```


```{r, warning=FALSE}
#making a copy without the merged double types, after selecting the resisting types
tempEffectiveness2 <- tempEffectivenessResistant[-dim(tempEffectivenessResistant)[1],]

#creating logic dataframe checking if each individual type is a resistor
tempEffectiveness2Logic <- data.frame(tempEffectiveness2 < 1)
tempEffectiveness2Logic$attacking.defending <- tempEffectiveness2$attacking.defending
tempEffectiveness2Logic

#making a list of single type resistors
singleTypeResistors <- c()

#making lists of dual type resistors
dualTypeResistorsFirsts <- c()
dualTypeResistorsSeconds <- c()

#if all the values in the column in tempEffectiveness2Logic are TRUE,
#then we can add corresponding type to the list of single type resistors
for (i in 2:dim(tempEffectiveness2)[2]){
    if ( all(unlist(tempEffectiveness2Logic[i])) ){
        singleTypeResistors <- c(singleTypeResistors, colnames(tempEffectiveness2Logic)[i])
    }
    
    if (tempEffectiveness2Logic[1,i]) {
        dualTypeResistorsFirsts <- c(dualTypeResistorsFirsts, colnames(tempEffectiveness2Logic)[i])
    } else {
        dualTypeResistorsSeconds<- c(dualTypeResistorsSeconds, colnames(tempEffectiveness2Logic)[i])
    }
    
    if (tempEffectiveness2Logic[2,i]) {
        dualTypeResistorsSeconds<- c(dualTypeResistorsSeconds, colnames(tempEffectiveness2Logic)[i])
    } else {
        dualTypeResistorsFirsts <- c(dualTypeResistorsFirsts, colnames(tempEffectiveness2Logic)[i])
    }
}

dualTypeResistorsFirsts <- unique(dualTypeResistorsFirsts)
dualTypeResistorsSeconds <- unique(dualTypeResistorsSeconds)

dualTypeResistors <- expand.grid(dualTypeResistorsFirsts, dualTypeResistorsSeconds)
colnames(dualTypeResistors) <- c('first', 'second')
dualTypeResistors$first <- as.character(dualTypeResistors$first)
dualTypeResistors$second <- as.character(dualTypeResistors$second)
dualTypeResistors <- dualTypeResistors[dualTypeResistors$first != dualTypeResistors$second,]

rm(tempEffectivenessResistant, tempEffectiveness2, tempEffectiveness2Logic)
```

```{r}
singleTypeResistors
```
```{r}
dualTypeResistors
```

### Resistor pokemon

```{r}

statsDataResistors <- typeData[1,]
statsDataResistors <- statsDataResistors[-1,]

# for (i in 1:length(singleTypeResistors)){
#     statsDataResistors <- rbind( statsDataResistors,
#                                  typeData[typeData$Type == singleTypeResistors[i],] )
# }

for (i in 1:length(singleTypeResistors)){
    statsDataResistors <- rbind( statsDataResistors,
                                 typeData[grep(singleTypeResistors[i], typeData$Type),] )
}

statsDataResistors
```

```{r}

statsDataResistors <- typeData[1,]
statsDataResistors <- statsDataResistors[-1,]

for (i in 1:dim(dualTypeResistors)[1]){
    statsDataResistors <- rbind( statsDataResistors,
                                 typeData[grepl(dualTypeResistors$first[i], typeData$Type) &
                                              grepl(dualTypeResistors$second[i], typeData$Type),] )
}

statsDataResistors
```

